---@class FrameworkUtils
---@field get_treesitter_queries function the TS queries for the framework
---@field build_position function Builds a position from captured nodes based on framework specific rules
