describe("Test environment", function()
  it("Test can access vim namespace", function()
    assert(vim, "Cannot access vim namespace")
    assert.are.same(vim.trim("  a "), "a")
  end)
  it("Test can access neotest dependency", function()
    assert(require("neotest"), "neotest")
  end)
  it("Test can access module in lua/neotest-dotnet", function()
    assert(require("neotest-dotnet"), "Could not access main module")
  end)
end)
